version: 2

buildSteps: &buildSteps
  - setup_remote_docker
  - checkout
  - run:
      name: install-npm
      command: npm install
  - run:
      name: test
      command: npm test

jobs:
  "node-6":
    docker:
      - image: circleci/node:6
    working_directory: ~/node-6
    steps: *buildSteps

  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/node-8
    steps: *buildSteps

workflows:
  version: 2
  build:
    jobs:
      - "node-6":
          # Run for all tags (required to allow the deploy to trigger on version tags)
          filters:
            tags:
              only: /.*/
      - "node-8":
          # Run for all tags (required to allow the deploy to trigger on version tags)
          filters:
            tags:
              only: /.*/